<?php

/**
 * @file
 * Module: 'udla_menuimage'
 *
 * When editing a menu link, this module provides a file field
 * to upload an image to associate with a menu item. In the
 * array returned by menu_link_load, the fid of the image file
 * is contained in [options][content][image]. This may may be
 * passed as a parameter to file_load to obtain its public:// uri,
 * and further used with either file_build_uri or image_style_url
 * to populate the src= attribute of an <img>.
 */

/**
 * Implements hook_form_menu_edit_item_alter().
 *
 * add field to upload an image for menu item
 */
function udla_menuimage_form_menu_edit_item_alter(&$form, &$form_state)
{
  $mlid = (isset($form['mlid']['#value']) ? $form['mlid']['#value'] : 0);
  $fid = 0;
  $file = false;
  if ($mlid && ($result = db_query("
    SELECT options FROM {menu_links}
    WHERE mlid = :mlid
    LIMIT 1
  ", array(':mlid' => $mlid))->fetchField())) {
    $options = unserialize($result);
    $fid = (isset($options['content']['image']) ? $options['content']['image'] : 0);
    if (!($file = file_load($fid))) {
      $fid = 0;
    }
  }
  foreach ($form as $name => $element) {
    $temp[$name] = $element;
    if ($name == "description") {
      $blank = ("/" . drupal_get_path("module", "udla_menuimage") . "/blank.gif");
      drupal_add_js(array('udla_menuimageBlank' => $blank), "setting");
      $temp['udla_menuimage'] = array(
        '#type' => 'media',
        '#title' => t('Choose a file'),
        '#description' => t('Choose a file'),
        '#tree' => TRUE,
        '#input' => TRUE,
        '#media_options' => array(
          'global' => array(
            'types' => array(
              'image' => 'image',
              'video' => 'video',
              'audio' => 'audio',
              'document' => 'document',
            ),
            'schemes' => array(
              'public' => 'public',
            ),
            'enabledPlugins' => array(
              'upload' => 'upload',
            ),
          ),
        ),
        '#default_value' => $fid,
      );
    }
  }
  $form = $temp;
  $form['#submit'][] = "udla_menuimage_edit_item_submit";
}

/**
 * Callback for udla_menuimage_form_menu_edit_item_alter().
 *
 * handle "Save" submit; create entry in menu item options array
 * that refers to uploaded image; uses separate 'content' array
 * within options, to differentiate from 'attributes'
 */
function udla_menuimage_edit_item_submit(&$form, &$form_state)
{
  if (isset($form_state['values']['udla_menuimage']) && isset($form_state['values']['mlid'])) {
    $mlid = $form_state['values']['mlid'];
    if ($mlid && ($result = db_query("
      SELECT options FROM {menu_links}
      WHERE mlid = :mlid
      LIMIT 1
    ", array(':mlid' => $mlid))->fetchField())) {
      $options = unserialize($result);
      $fid = (0 + preg_replace("/[^0-9]/", "", $form_state['values']['udla_menuimage']));
      if ($fid != 0) {
        if (!array_key_exists("content", $options)) {
          $options['content'] = array();
        }
        $options['content']['image'] = $fid;
        if ($file = file_load($fid)) {
          $file->status = FILE_STATUS_PERMANENT;
          file_save($file);
          file_usage_add($file, "udla_menuimage", "menu", $mlid);
        }
      } else {
        if (isset($options['content']['image'])) {
          if ($file = file_load($options['content']['image'])) {
            file_usage_delete($file, "udla_menuimage");
            file_delete($file);
          }
          unset($options['content']['image']);
        }
      }
      $options = serialize($options);
      if ($options != $result) {
        db_update("menu_links")
          ->fields(array('options' => $options))
          ->condition("mlid", $mlid, "=")
          ->execute();
      }
    }
    //$form_state['redirect'] = ("/admin/structure/menu/item/" . $mlid . "/edit");
  }
}
